[package]
name = "simplified_swap_program"
version = "0.1.0"
edition = "2021"
description = "Simplified SOL to YOT swap program"

[features]
no-entrypoint = []

[dependencies]
solana-program = "1.16.0"
thiserror = "1.0.40"
spl-token = { version = "4.0", features = ["no-entrypoint"] }
borsh = "0.10.3"
arrayref = "0.3.7"

[lib]
crate-type = ["cdylib", "lib"]